export {default as Home} from '../pages/Home/Home'
export {default as Login} from '../pages/Login/Login'
export {default as ForgotPassword} from '../pages/Login/ForgotPassword'
export {default as ConfirmPassword} from '../pages/Login/ConfirmPassword'
export {default as Confirm} from "../pages/Login/Confirm"
export {default as AdminConfirm} from '../pages/Login/AdminConfirm'
export {default as Signup} from '../pages/Signup/Signup'
export {default as Promotion1} from '../pages/Promotion/Promotion1'
export {default as Courses} from '../pages/Courses/Courses'
export {default as Dashboard} from '../pages/Dashboard/Dashboard'
export {default as PhysicalClasses} from '../pages/PhysicalClasses/PhysicalClasses'
export {default as StudentPortal} from '../pages/Portal/StudentPortal'
export {default as AdminAccess} from '../pages/Portal/AdminAccess'
export {default as AdminPortal} from '../pages/Portal/AdminPortal'
export {default as CourseContent} from '../pages/CourseContent/CourseContent'
export {default as StudentCourseContent} from '../pages/CourseContent/StudentCourseContent'
export {default as StudentCourse} from '../pages/CourseContent/StudentCourse'
export {default as Enroll} from '../pages/Enroll/Enroll'
export {default as Direct} from '../pages/Forums/Direct'
export {default as VIPForum} from '../pages/Forums/VIP'
export {default as Chat} from '../pages/Forums/Chat'
export {default as Admin} from '../pages/Forums/Admin'
export {default as AdminChat} from '../pages/Forums/AdminChat'
export {default as Profile} from '../pages/Profile/Profile'
export {default as Upload} from '../pages/Upload/Upload'
export {Preview} from '../pages/Upload/Preview'
export {default as Landing} from '../pages/Home/Landing'


export {default as Members} from '../pages/Portal/Members'
export {default as Payments} from '../pages/Portal/Payments'
export {default as Direct2} from '../pages/Portal/Direct2'
export {default as Chats} from '../pages/Portal/Chats'
export {default as VipChats} from '../pages/Portal/VipChats'
export {default as Adminn} from '../pages/Portal/Adminn'
export {default as Chatty2} from '../pages/Portal/Chatty2'
export {default as AdminContent} from '../pages/Portal/AdminContent'

export {default as Terms} from '../pages/Terms/Terms'
export {default as Privacy} from '../pages/Terms/Privacy'
export {default as Refund} from '../pages/Terms/Refund'
export {default as Reports} from '../pages/Portal/Reports'
export {default as BinaryBots} from '../pages/BinaryBots/BinaryBots'
export {default as ForexBots} from '../pages/ForexBots/ForexBots'
export {default as ExpertAdvisor} from '../pages/ExpertAdvisor/ExpertAdvisor'
export {default as TradingStrategies} from '../pages/TradingStrategies/TradingStrategies'
export {default as Referral} from '../pages/Referral/Referral'
export {default as Response} from '../pages/Response/Response'
export {default as UserMessage} from '../pages/Portal/UserMessage'
export {default as Uploads} from "../pages/Portal/Uploads"
export {default as Data} from "../pages/Portal/Data"
export {default as AddMedia} from '../pages/Portal/AddMedia'

export {default as ContentAdmin2} from '../pages/Portal/ContentAdmin2'
export {default as AdminBots} from '../pages/Portal/AdminBots'
export {default as FreeClasses} from '../pages/FreeClasses/FreeClasses'
export {default as FreeClass} from '../pages/Portal/FreeClass'
export {default as Subscriptions} from '../pages/Portal/Subscriptions'
export {default as AddUser} from '../pages/Portal/AddUser'
export {default as SendEmail} from '../pages/Portal/SendEmail'
export {default as Unsubscribe} from '../pages/Unsubscribe/Unsubscribe'
export {default as Forex} from '../pages/SEO/Forex'
export {default as TradePlatform} from '../pages/SEO/TradePlatform'
export {default as Trading} from '../pages/SEO/Trading'


